toto

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -103,15 +103,18 @@ jobs:
       - name: Validate inputs
         run: |
           if [[ '{{ inputs.branch-regex }}' != *'%(date)'* ]]; then
-            echo "::error::Input 'branch-regex' must contain exactly the string '%(date)'."
+            echo "::error::Input 'branch-regex' must contain exactly the string '%(date)', '${{ inputs.branch-regex }}' was provided."
+            exit 1
           fi
 
           if [[ '${{ inputs.image-template }}' != *'%(date)'* ]]; then
-            echo "::error::Input 'image-template' must contain exactly the string '%(date)'."
+            echo "::error::Input 'image-template' must contain exactly the string '%(date)', '${{ inputs.image-template }}' was provided."
+            exit 1
           fi
           
           if [[ '{{ inputs.slack-channels }}' != '' && '{{ secrets.SLACK_APP_TOKEN }}' == '' ]]; then
             echo "::error::Secret 'SLACK_APP_TOKEN' is mandatory if input 'slack-channels' is provided.'"
+            exit 1
           fi
 
       - name: Checkout repository
